apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-consumer-config
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-headless.kafka.svc.cluster.local:9092"
  KAFKA_SOURCE_TOPIC: "user-login"
  KAFKA_DESTINATION_TOPIC: "processed-logins"
  KAFKA_CONSUMER_GROUP: "user-login-processor"
  LOG_LEVEL: "INFO"
  METRICS_PORT: "8000"